import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  addIcon: {
    height: 25,
    position: 'absolute',
    right: -12.5,
    top: 81,
    width: 25,
  },
  bgImage: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  checkBtn: {
    color: '#1B4371',
    fontFamily: 'Roboto-Regular',
  },
  container: {
    flex: 1,
  },
  formInput: {
    backgroundColor: '#F6F6F6',
    borderColor: '#E8E8E8',
    borderRadius: 8,
    borderWidth: 1,
    fontFamily: 'Roboto-Regular',
    paddingBottom: 15,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    position: 'relative',
  },
  formWrapper: {
    gap: 16,
    marginBottom: 43,
    width: '100%',
  },
  inputFocused: {
    backgroundColor: '#fff',
    borderColor: '#FF6C00',
    borderRadius: 8,
    borderWidth: 1,
    fontFamily: 'Roboto-Regular',
    paddingBottom: 15,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    position: 'relative',
  },

  photoWrapper: {
    backgroundColor: '#F6F6F6',
    borderRadius: 16,
    height: 120,
    position: 'absolute',
    top: -60,
    width: 120,
  },
  registrationContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    height: 549,
    paddingBottom: 78,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 92,
    position: 'relative',
  },
  showPasswordBtn: {
    bottom: 20,
    color: '#1B4371',
    fontFamily: 'Roboto-Regular',
    position: 'absolute',
    right: 16,
  },
  submitBtn: {
    alignItems: 'center',
    backgroundColor: '#FF6C00',
    borderRadius: 100,
    display: 'flex',
    height: 51,
    justifyContent: 'center',
    marginBottom: 16,
    width: '100%',
  },
  submitBtnText: {
    color: '#fff',
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
  },
  title: {
    fontFamily: 'Roboto-Medium',
    fontSize: 30,
    marginBottom: 33,
  },
});
